language: node_js
node_js:
  - "8.1.3"
before_install:
  - npm install -g gulp
  - npm install -g gulp-cli
  - npm -g ls
script: gulp
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8